### ISSUE TITLE
Errors with windows_firewall_group resource:  undefined method `empty?' for nil:NilClass

### ISSUE THREAD

**Issue by davidasimon** [webalexeu/puppet-windows_firewall#21]
Added v1.3.2 of this module to the puppetfile of my test branch.  Added the example code to my manifest:

```
    windows_firewall_group { "File and Printer Sharing" :
      enabled => false,
    }
```

When I run the code on a Windows 2019 server, I get these error messages:

WARNING:  Skipping because provider prefetch failed
ERROR:  Could not prefetch windows_firewall_group provider 'windows_firewall_group': undefined method `empty?' for nil:NilClass

**Comment by webalexeu** [comment]
@davidasimon Fixed in v1.3.3
