### ISSUE TITLE
Cannot add multiple icmp_type in the same firewall rule

### ISSUE THREAD

**Issue by Daymarvi** [webalexeu/puppet-windows_firewall#31]
Hello,

I have a firewall rule that allow icmp type 8 (Echo Request), see my example below
```
'Allow icmpv4 ': 
direction: 'inbound' 
protocol: 'icmpv4' 
icmp_type: '8' 
hosts: 'myip' 
interface: 'any' 
description: 'Allow ICMPv4'
```

We need to allow icmpv4 type 3 and 11. But when i'm adding it into the icmp_type, i have an error : 
`Error: Could not run: undefined method `downcase' for {"value"=>["8", "10", "11"], "Count"=>3}:Hash`
I would like to avoid creating duplicate rules of course :-)

To reproduce it :
- open the firewall console
- create a new icmpv4 rule and add custom type
- type puppet ressource windows_firewall rule to get the output.

Would be nice to have something like that

```
'Allow icmpv4 ': 
direction: 'inbound' 
protocol: 'icmpv4' 
icmp_type: 
- '8' 
- '3:4'
- '11'
hosts: 'myip' 
interface: 'any' 
description: 'Allow ICMPv4'
```

The idea would be to manage the code and maybe the the type ? like referenced here : https://www.inetdoc.net/guides/iptables-tutorial/icmptypes.html

**Comment by webalexeu** [comment]
Bug confirmed

icmp_type is indeed an array of values
